language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - sudo apt-get install -y gearman-job-server
  - composer install

script:
  - bin/phpunit --coverage-text --verbose
  - bin/php-cs-fixer fix --dry-run --diff -vv

sudo: true
dist: trusty

notifications:
  email:
    - travis@b-zik.de


